### ISSUE TITLE
DLIO not able to see IOR events

### ISSUE THREAD

**Issue by vsoch** [hariharan-devarajan/dlio-profiler#50]
I have DLIO running alongside IOR, with the following setup:

```console
             apt-get install -y python3-pip hwloc libhwloc-dev
             DLP_VERSION=dev
             python3 -m pip install git+https://github.com/hariharan-devarajan/dlio-profiler.git@${DLP_VERSION}      
             mkdir -p /opt/logs
             export DLIO_PROFILER_LOG_LEVEL=ERROR
             export DLIO_PROFILER_LOG_LEVEL=DEBUG
             export DLIO_PROFILER_ENABLE=1
             export DLIO_PROFILER_INC_METADATA=1
             export DLIO_PROFILER_INIT=PRELOAD
             export DLIO_PROFILER_DATA_DIR=/opt/ior
             export DLIO_PROFILER_LOG_FILE=/opt/logs/ior-profile.pfw
             sleep 10
             export PRELOAD_PATH=$(find /usr -name libdlio_profiler_preload.so)  
             echo "preload path is $PRELOAD_PATH"
```

And then to run ior:

```
      command: LD_PRELOAD=$PRELOAD_PATH ior -k -w -r -o testfile > out.txt
```
But there is no data in my /opt/logs. When I change the profiler data dir to "all" I see output. So I think there is a bug. Thanks!

**Comment by hariharan-devarajan** [comment]
@vsoch Thanks for reporting. I was able to run IOR and trace. Look at https://github.com/hariharan-devarajan/dlio-profiler/blob/dev/docker/ior.Dockerfile

The main issue your having is that IOR is creating relative files in the directory your in. This makes data_dir screw up. Let me know if you still face any issues.

**Comment by hariharan-devarajan** [comment]
@vsoch Did this fix work for u. If so should I close it?

**Comment by vsoch** [comment]
Yes we are good, thanks!
